name: Build .wsl image
on:
  push:
    branches: [release]
jobs:
  build_and_release_image:
    runs-on: ubuntu-latest
    env:
        AMD64_SOURCE: 'https://releases.ubuntu.com/noble/ubuntu-24.04.2-wsl-amd64.wsl'
        ARM64_SOURCE: 'https://cdimages.ubuntu.com/releases/24.04.2/release/ubuntu-24.04.2-wsl-arm64.wsl'
        CLOUD_CONFIG_DEST_DIR_PATH: /etc/cloud/cloud.cfg.d/ # the path to the Linux folder where the cloud-init file goes, with trailing slash
        CLOUD_CONFIG_REPO_FILE_PATH: 995_uncc_itsc_3146.cfg # the path to the cloud-init file within the GitHub repo
    steps:
    
      - name: Download the base Ubuntu image
        run: |
          mkdir imgs/
          wget -O imgs/amd64.wsl $AMD64_SOURCE
          wget -O imgs/arm64.wsl $ARM64_SOURCE
          
      - name: Make the files in this commit available to the current directory
        uses: actions/checkout@v4
        with:
          path: repo/
        
      - name: Add the cloud-init file to the images
        run: |
          tar --append -f imgs/amd64.wsl --transform '$SED_EXPRESSION' $SOURCE_FILE
          tar --append -f imgs/arm64.wsl --transform '$SED_EXPRESSION' $SOURCE_FILE
        env:
          SED_EXPRESSION: ${{ format('s/^.*\//{0}/', vars.CLOUD_CONFIG_DEST_DIR_PATH) }} # replace the directory part with the dest_dir_path
          SOURCE_FILE: ${{ join('repo/', vars.CLOUD_CONFIG_REPO_FILE_PATH) }}

      - name: Create Release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ vars.VERSION_ID }}
          release_name: Release ${{ vars.VERSION_ID }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_ID: ${{ join('v0.0.', github.ref) }}
        
